"""  Created on 06/09/2022::
------------- mappings -------------
**Authors**: W. Wakker

"""

oecd_sector_2022_2021_mapping = {'A01_02': '01T02',
                                 'A03': '03',
                                 'B05_06': '05T06',
                                 'B07_08': '07T08',
                                 'B09': '09',
                                 'C10T12': '10T12',
                                 'C13T15': '13T15',
                                 'C16': '16',
                                 'C17_18': '17T18',
                                 'C19': '19',
                                 'C20': '20',
                                 'C21': '21',
                                 'C22': '22',
                                 'C23': '23',
                                 'C24': '24',
                                 'C25': '25',
                                 'C26': '26',
                                 'C27': '27',
                                 'C28': '28',
                                 'C29': '29',
                                 'C30': '30',
                                 'C31T33': '31T33',
                                 'D': '35',
                                 'E': '36T39',
                                 'F': '41T43',
                                 'G': '45T47',
                                 'H49': '49',
                                 'H50': '50',
                                 'H51': '51',
                                 'H52': '52',
                                 'H53': '53',
                                 'I': '55T56',
                                 'J58T60': '58T60',
                                 'J61': '61',
                                 'J62_63': '62T63',
                                 'K': '64T66',
                                 'L': '68',
                                 'M': '69T75',
                                 'N': '77T82',
                                 'O': '84',
                                 'P': '85',
                                 'Q': '86T88',
                                 'R': '90T93',
                                 'S': '94T96',
                                 'T': '97T98'}

oecd_sector_name_mapping = {'01T02': 'Agriculture, hunting, forestry',
                            '03': 'Fishing and aquaculture',
                            '05T06': 'Mining and quarrying, energy producing products',
                            '07T08': 'Mining and quarrying, non-energy producing products',
                            '09': 'Mining support service activities',
                            '10T12': 'Food products, beverages and tobacco',
                            '13T15': 'Textiles, textile products, leather and footwear',
                            '16': 'Wood and products of wood and cork',
                            '17T18': 'Paper products and printing',
                            '19': 'Coke and refined petroleum products',
                            '20': 'Chemical and chemical products',
                            '21': 'Pharmaceuticals, medicinal chemical and botanical products',
                            '22': 'Rubber and plastics products',
                            '23': 'Other non-metallic mineral products',
                            '24': 'Basic metals',
                            '25': 'Fabricated metal products',
                            '26': 'Computer, electronic and optical equipment',
                            '27': 'Electrical equipment',
                            '28': 'Machinery and equipment, nec ',
                            '29': 'Motor vehicles, trailers and semi-trailers',
                            '30': 'Other transport equipment',
                            '31T33': 'Manufacturing nec; repair and installation of machinery and equipment',
                            '35': 'Electricity, gas, steam and air conditioning supply',
                            '36T39': 'Water supply; sewerage, waste management and remediation activities',
                            '41T43': 'Construction',
                            '45T47': 'Wholesale and retail trade; repair of motor vehicles',
                            '49': 'Land transport and transport via pipelines',
                            '50': 'Water transport',
                            '51': 'Air transport',
                            '52': 'Warehousing and support activities for transportation',
                            '53': 'Postal and courier activities',
                            '55T56': 'Accommodation and food service activities',
                            '58T60': 'Publishing, audiovisual and broadcasting activities',
                            '61': 'Telecommunications',
                            '62T63': 'IT and other information services',
                            '64T66': 'Financial and insurance activities',
                            '68': 'Real estate activities',
                            '69T75': 'Professional, scientific and technical activities',
                            '77T82': 'Administrative and support services',
                            '84': 'Public administration and defence; compulsory social security',
                            '85': 'Education',
                            '86T88': 'Human health and social work activities',
                            '90T93': 'Arts, entertainment and recreation',
                            '94T96': 'Other service activities',
                            '97T98': 'Activities of households as employers; undifferentiated goods- and '
                                     'services-producing activities of households for own use'}

oecd_sector_name_mapping_simple = {'01T02': 'Agriculture, hunting, forestry',
                                   '03': 'Fishing',
                                   '05T06': 'Mining and quarrying',
                                   '07T08': 'Mining and quarrying, non-energy producing products',
                                   '09': 'Mining support',
                                   '10T12': 'Food products, beverages and tobacco',
                                   '13T15': 'Textiles',
                                   '16': 'Wood products',
                                   '17T18': 'Paper products and printing',
                                   '19': 'Coke and refined petroleum products',
                                   '20': 'Chemicals',
                                   '21': 'Pharmaceuticals',
                                   '22': 'Rubber and plastics products',
                                   '23': 'Other non-metallic mineral products',
                                   '24': 'Basic metals',
                                   '25': 'Fabricated metal products',
                                   '26': 'Computer, electronic and optical equipment',
                                   '27': 'Electrical equipment',
                                   '28': 'Machinery and equipment, nec',
                                   '29': 'Motor vehicles',
                                   '30': 'Other transport equipment',
                                   '31T33': 'Manufacturing nec',
                                   '35': 'Electricity, gas, steam and air conditioning supply',
                                   '36T39': 'Water supply and waste management',
                                   '41T43': 'Construction',
                                   '45T47': 'Wholesale and retail trade',
                                   '49': 'Land transport',
                                   '50': 'Water transport',
                                   '51': 'Air transport',
                                   '52': 'Warehousing',
                                   '53': 'Postal services',
                                   '55T56': 'Accommodation',
                                   '58T60': 'Publishing, audiovisual and broadcasting activities',
                                   '61': 'Telecommunications',
                                   '62T63': 'IT services',
                                   '64T66': 'Financial and insurance activities',
                                   '68': 'Real estate',
                                   '69T75': 'Professional, scientific and technical activities',
                                   '77T82': 'Administrative services',
                                   '84': 'Public administration and defence',
                                   '85': 'Education',
                                   '86T88': 'Human health and social work activities',
                                   '90T93': 'Arts, entertainment and recreation',
                                   '94T96': 'Other service activities',
                                   '97T98': 'Households'}

oecd_demand_items = {'HFCE': 'Household Final Consumption Expenditure',
                     'NPISH': 'Non-Profit Institutions Serving Households',
                     'GGFC': 'General Government Final Consumption',
                     'GFCF': 'Gross Fixed Capital Formation',
                     'INVNT': 'Changes in Inventories and Valuables',
                     'DPABR': 'Direct purchases abroad by residents'}

nace2_to_oecd_sector = {v: k for k, vs in {
    x: [f'{y:02.0f}' for y in list(range(int(x.split('T')[0]), int(x.split('T')[1]) + 1))] if 'T' in x else [x] for x in
    oecd_sector_name_mapping.keys()}.items() for v in vs}

figaro_sector_name_mapping_ixi_2022 = {
    'A01': 'Crop and animal production, hunting and related service activities',
    'A02': 'Forestry and logging',
    'A03': 'Fishing and aquaculture',
    'B': 'Mining and quarrying',
    'C10T12': 'Manufacture of food products; beverages and tobacco products',
    'C13T15': 'Manufacture of textiles, wearing apparel, leather and related products',
    'C16': 'Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials',
    'C17': 'Manufacture of paper and paper products',
    'C18': 'Printing and reproduction of recorded media',
    'C19': 'Manufacture of coke and refined petroleum products',
    'C20': 'Manufacture of chemicals and chemical products',
    'C21': 'Manufacture of basic pharmaceutical products and pharmaceutical preparations',
    'C22': 'Manufacture of rubber and plastic products',
    'C23': 'Manufacture of other non-metallic mineral products',
    'C24': 'Manufacture of basic metals',
    'C25': 'Manufacture of fabricated metal products, except machinery and equipment',
    'C26': 'Manufacture of computer, electronic and optical products',
    'C27': 'Manufacture of electrical equipment',
    'C28': 'Manufacture of machinery and equipment n.e.c.',
    'C29': 'Manufacture of motor vehicles, trailers and semi-trailers',
    'C30': 'Manufacture of other transport equipment',
    'C31_32': 'Manufacture of furniture; other manufacturing',
    'C33': 'Repair and installation of machinery and equipment',
    'D35': 'Electricity, gas, steam and air conditioning supply',
    'E36': 'Water collection, treatment and supply',
    'E37T39': 'Sewerage, waste management, remediation activities',
    'F': 'Construction',
    'G45': 'Wholesale and retail trade and repair of motor vehicles and motorcycles',
    'G46': 'Wholesale trade, except of motor vehicles and motorcycles',
    'G47': 'Retail trade, except of motor vehicles and motorcycles',
    'H49': 'Land transport and transport via pipelines',
    'H50': 'Water transport',
    'H51': 'Air transport',
    'H52': 'Warehousing and support activities for transportation',
    'H53': 'Postal and courier activities',
    'I': 'Accommodation and food service activities',
    'J58': 'Publishing activities',
    'J59_60': 'Motion picture, video, television programme production; programming and broadcasting activities',
    'J61': 'Telecommunications',
    'J62_63': 'Computer programming, consultancy, and information service activities',
    'K64': 'Financial service activities, except insurance and pension funding',
    'K65': 'Insurance, reinsurance and pension funding, except compulsory social security',
    'K66': 'Activities auxiliary to financial services and insurance activities',
    'L': 'Real estate activities',
    'M69_70': 'Legal and accounting activities; activities of head offices; management consultancy activities',
    'M71': 'Architectural and engineering activities; technical testing and analysis',
    'M72': 'Scientific research and development',
    'M73': 'Advertising and market research',
    'M74_75': 'Other professional, scientific and technical activities; veterinary activities',
    'N77': 'Rental and leasing activities',
    'N78': 'Employment activities',
    'N79': 'Travel agency, tour operator reservation service and related activities',
    'N80T82': 'Security and investigation, service and landscape, office administrative and support activities',
    'O84': 'Public administration and defence; compulsory social security',
    'P85': 'Education',
    'Q86': 'Human health activities',
    'Q87_88': 'Residential care activities and social work activities without accommodation',
    'R90T92': 'Creative, arts and entertainment activities; libraries, archives, museums and other cultural activities; gambling and betting activities',
    'R93': 'Sports activities and amusement and recreation activities',
    'S94': 'Activities of membership organisations',
    'S95': 'Repair of computers and personal and household goods',
    'S96': 'Other personal service activities',
    'T': 'Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use',
    'U': 'Activities of extraterritorial organisations and bodies'
}

figaro_sector_name_mapping_simple = {
    'A01': 'Crop and animal production',
    'A02': 'Forestry and logging',
    'A03': 'Fishing and aquaculture',
    'B': 'Mining and quarrying',
    'C10T12': 'Manufacture of food products',
    'C13T15': 'Manufacture of textiles',
    'C16': 'Manufacture of wood',
    'C17': 'Manufacture of paper',
    'C18': 'Printing and reproduction of recorded media',
    'C19': 'Manufacture of coke and refined petroleum products',
    'C20': 'Manufacture of chemicals and chemical products',
    'C21': 'Manufacture of basic pharmaceutical products',
    'C22': 'Manufacture of rubber and plastic products',
    'C23': 'Manufacture of other non-metallic mineral products',
    'C24': 'Manufacture of basic metals',
    'C25': 'Manufacture of fabricated metal products',
    'C26': 'Manufacture of computer, electronic and optical products',
    'C27': 'Manufacture of electrical equipment',
    'C28': 'Manufacture of machinery and equipment n.e.c.',
    'C29': 'Manufacture of motor vehicles, trailers and semi-trailers',
    'C30': 'Manufacture of other transport equipment',
    'C31_32': 'Manufacture of furniture; other manufacturing',
    'C33': 'Repair and installation of machinery and equipment',
    'D35': 'Electricity, gas, steam and air conditioning supply',
    'E36': 'Water collection, treatment and supply',
    'E37T39': 'Sewerage, waste management, remediation activities',
    'F': 'Construction',
    'G45': 'Wholesale and retail trade and repair of motor vehicles and motorcycles',
    'G46': 'Wholesale trade, except of motor vehicles and motorcycles',
    'G47': 'Retail trade, except of motor vehicles and motorcycles',
    'H49': 'Land transport and transport via pipelines',
    'H50': 'Water transport',
    'H51': 'Air transport',
    'H52': 'Warehousing and support activities for transportation',
    'H53': 'Postal and courier activities',
    'I': 'Accommodation and food service activities',
    'J58': 'Publishing activities',
    'J59_60': 'Motion picture, video, television programme production',
    'J61': 'Telecommunications',
    'J62_63': 'Computer programming, consultancy, and information service activities',
    'K64': 'Financial service activities, except insurance and pension funding',
    'K65': 'Insurance, reinsurance and pension funding, except compulsory social security',
    'K66': 'Activities auxiliary to financial services and insurance activities',
    'L': 'Real estate activities',
    'M69_70': 'Legal and accounting activities',
    'M71': 'Architectural and engineering activities',
    'M72': 'Scientific research and development',
    'M73': 'Advertising and market research',
    'M74_75': 'Other professional, scientific and technical activities',
    'N77': 'Rental and leasing activities',
    'N78': 'Employment activities',
    'N79': 'Travel agency, tour operator reservation service',
    'N80T82': 'Security and investigation',
    'O84': 'Public administration and defence; compulsory social security',
    'P85': 'Education',
    'Q86': 'Human health activities',
    'Q87_88': 'Residential care activities and social work activities',
    'R90T92': 'Creative, arts and entertainment activities',
    'R93': 'Sports activities and amusement and recreation activities',
    'S94': 'Activities of membership organisations',
    'S95': 'Repair of computers and personal and household goods',
    'S96': 'Other personal service activities',
    'T': 'Activities of households as employers',
    'U': 'Activities of extraterritorial organisations and bodies'}

figaro_demand_items = {'P3_S13': 'Final consumption expenditure by government',
                       'P3_S14': 'Final consumption expenditure by households',
                       'P3_S15': 'Final consumption expenditure by non-profit organisations serving households (NPISH)',
                       'P51G': 'Gross fixed capital formation',
                       'P5M': 'Changes in inventories and acquisition less disposals of valuables'}

figaro_sector_name_mapping_pxp_2022 = {'CPA_A01': 'Products of agriculture, hunting and related services',
                                  'CPA_A02': 'Products of forestry, logging and related services',
                                  'CPA_A03': 'Fish and other fishing products; aquaculture products; support services to fishing',
                                  'CPA_B': 'Mining and quarrying',
                                  'CPA_C10T12': 'Food, beverages and tobacco products',
                                  'CPA_C13T15': 'Textiles, wearing apparel, leather and related products',
                                  'CPA_C16': 'Wood and of products of wood and cork, except furniture; articles of straw and plaiting materials',
                                  'CPA_C17': 'Paper and paper products',
                                  'CPA_C18': 'Printing and recording services',
                                  'CPA_C19': 'Coke and refined petroleum products',
                                  'CPA_C20': 'Chemicals and chemical products',
                                  'CPA_C21': 'Basic pharmaceutical products and pharmaceutical preparations',
                                  'CPA_C22': 'Rubber and plastic products',
                                  'CPA_C23': 'Other non-metallic mineral products',
                                  'CPA_C24': 'Basic metals',
                                  'CPA_C25': 'Fabricated metal products, except machinery and equipment',
                                  'CPA_C26': 'Computer, electronic and optical products',
                                  'CPA_C27': 'Electrical equipment',
                                  'CPA_C28': 'Machinery and equipment n.e.c.',
                                  'CPA_C29': 'Motor vehicles, trailers and semi-trailers',
                                  'CPA_C30': 'Other transport equipment',
                                  'CPA_C31_32': 'Furniture and other manufactured goods',
                                  'CPA_C33': 'Repair and installation services of machinery and equipment',
                                  'CPA_D35': 'Electricity, gas, steam and air conditioning',
                                  'CPA_E36': 'Natural water; water treatment and supply services',
                                  'CPA_E37T39': 'Sewerage services; sewage sludge; waste collection, treatment and disposal services; materials recovery services; remediation services and other waste',
                                  'CPA_F': 'Constructions and construction works',
                                  'CPA_G45': 'Wholesale and retail trade and repair services of motor vehicles and motorcycles',
                                  'CPA_G46': 'Wholesale trade services, except of motor vehicles and motorcycles',
                                  'CPA_G47': 'Retail trade services, except of motor vehicles and motorcycles',
                                  'CPA_H49': 'Land transport services and transport services via pipelines',
                                  'CPA_H50': 'Water transport services',
                                  'CPA_H51': 'Air transport services',
                                  'CPA_H52': 'Warehousing and support services for transportation',
                                  'CPA_H53': 'Postal and courier services',
                                  'CPA_I': 'Accommodation and food services',
                                  'CPA_J58': 'Publishing services',
                                  'CPA_J59_60': 'Motion picture, video and television programme production services, sound recording and music publishing; programming and broadcasting services',
                                  'CPA_J61': 'Telecommunications services',
                                  'CPA_J62_63': 'Computer programming, consultancy and related services; Information services',
                                  'CPA_K64': 'Financial services, except insurance and pension funding',
                                  'CPA_K65': 'Insurance, reinsurance and pension funding services, except compulsory social security',
                                  'CPA_K66': 'Services auxiliary to financial services and insurance services',
                                  'CPA_L': 'Real estate services',
                                  'CPA_M69_70': 'Legal and accounting services; services of head offices; management consultancy services',
                                  'CPA_M71': 'Architectural and engineering services; technical testing and analysis services',
                                  'CPA_M72': 'Scientific research and development services',
                                  'CPA_M73': 'Advertising and market research services',
                                  'CPA_M74_75': 'Other professional, scientific and technical services and veterinary services',
                                  'CPA_N77': 'Rental and leasing services',
                                  'CPA_N78': 'Employment services',
                                  'CPA_N79': 'Travel agency, tour operator and other reservation services and related services',
                                  'CPA_N80T82': 'Security and investigation services; services to buildings and landscape; office administrative, office support and other business support services',
                                  'CPA_O84': 'Public administration and defence services; compulsory social security services',
                                  'CPA_P85': 'Education services',
                                  'CPA_Q86': 'Human health services',
                                  'CPA_Q87_88': 'Residential care services; social work services without accommodation',
                                  'CPA_R90T92': 'Creative, arts, entertainment, library, archive, museum, other cultural services; gambling and betting services',
                                  'CPA_R93': 'Sporting services and amusement and recreation services',
                                  'CPA_S94': 'Services furnished by membership organisations',
                                  'CPA_S95': 'Repair services of computers and personal and household goods',
                                  'CPA_S96': 'Other personal services',
                                  'CPA_T': 'Services of households as employers; undifferentiated goods and services produced by households for own use',
                                  'CPA_U': 'Services provided by extraterritorial organisations and bodies'}
